global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerting_rules.yml"

scrape_configs:
  - job_name: "video-server-web"
    static_configs:
      - targets: ["web-service:8080"]
    metrics_path: /metrics
